#!/bin/bash

DISK_USAGE=$(df -hT | grep -v Filesystem) #cmd for check disc usage 
DISK_THRESHOLD=2 # in project we keep it as 75
IP_ADDRESS=$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4) #google it for aws instance ip
# -s uses silent output and dont show in result
MESSAGE=""

#output needed line by line so we use loop
while IFS= read -r line
do
    USAGE=$(echo $line | awk '{print $6}' | cut -d "%" -f1) #usage 6th row so $6 & "%" not needed so cut
    PARTITION=$(echo $line | awk '{print $7}')
    if [ $USAGE -ge $DISK_THRESHOLD ]; then
        MESSAGE+="High Disk usage on $PARTITION: $USAGE % <br>" # escaping   + appends  /n new line for linux <br> for new line in html
    fi
done <<< $DISK_USAGE

echo -e "Message Body: $MESSAGE"

sh mail.sh "ashokkumar1112090@gmail.com" "High Disk Usage Alert" "High Disk Usage" "$MESSAGE" "$IP_ADDRESS" "DevOps Team"

# TO_ADDRESS=$1 ashok
# SUBJECT=$2 disk usage
# ALERT_TYPE=$3 high disk
# MESSAGE_BODY=$4 message
# IP_ADDRESS=$5 ip